site_name: "Unofficial Drehmal: PRIMΩRDIAL Wiki"
site_description: "This is an unofficial wiki for Drehmal: PRIMΩRDIAL. See drehmal.net for more details."
site_url: https://wiki.drehmal.cyou
repo_url: https://github.com/drehmal/wiki
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.gif
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - navigation.instant

plugins:
  # provided by MkDocs
  - search
  # provided by Material theme
  - tags:
      tags_file: Overview.md
      enabled: !ENV [CI, false]
  - social:
      cards: !ENV [CI, false]
  # others
  - htmlproofer:
      enabled: !ENV [CI, false]
  - git-revision-date-localized:
      enabled: false # currently doesn't work with Cloudflare pages
      enable_creation_date: true
  - roamlinks 
  - minify:
      minify_html: !ENV [CI, false]
      minify_js: !ENV [CI, false]
      minify_css: !ENV [CI, false]
  - glightbox
  - redirects:
        redirect_maps:
            # 'abandoned_troupemaster.md': 'highfall.md'
            # 'acacia_merchant.md': 'athrah.md'
            'Achievements.md': 'Advancements.md'
            'Regions.md': 'World/Regions/index.md'
            'Settlements.md': 'World/Settlements/index.md'


markdown_extensions:
  - footnotes
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: include/
      #auto_append:
      #  - includes/abbreviations.md
      
extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/drehmal
      name: The official Drehmal Discord
  generator: false
